name: Python CI

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  
          
      - name: Run linter
        run: flake8 .  

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install codeclimate-test-reporter

      - name: Run tests
        run: pytest
          
      - name: Run tests with coverage
        run: |
          pytest --cov=diff tests/  # Замените my_module на Ваш модуль
          
      - name: Prepare coverage report
        run: codeclimate-test-reporter

      - name: Send coverage to Code Climate
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        run: codeclimate-test-reporter
